### ISSUE TITLE
Make a route and implement a script!

### ISSUE THREAD

**Issue by MaxProfit** [MaxProfit/IlliniFoodies-Frontend#1]
Hello Friends,

I want you to make a route where we can send people to after their successful authentication! 
The route can look something like `illinifoodies.xyz/successfulsignin` or something.
This route will then run the following code.

```javascript
// get the authentication token, the one used to make API calls!
id_token = location.hash.split('&')[0].split('=')[1];

// Set it into a cookie for the website named idtoken!
document.cookie = "idtoken=" + id_token;

// This function just removes everything after the illinifoodies.xyz to make
// it look pretty and keep the logic away from the users.
function removeHash () { 
    history.pushState("", document.title, window.location.pathname
                                                       + window.location.search);
}

removeHash();
```

**Comment by mskuybeda** [comment]
Hi, may I give it a try?

**Comment by MaxProfit** [comment]
@mskuybeda why not! Fork it and give it a try!

**Comment by MaxProfit** [comment]
`function getJsonFromUrl(url) {
  if(!url) url = location.href;
  var question = url.indexOf("?");
  var hash = url.indexOf("#");
  if(hash==-1 && question==-1) return {};
  if(hash==-1) hash = url.length;
  var query = question==-1 || hash==question+1 ? url.substring(hash) : 
  url.substring(question+1,hash);
  var result = {};
  query.split("&").forEach(function(part) {
    if(!part) return;
    part = part.split("+").join(" "); // replace every + with space, regexp-free version
    var eq = part.indexOf("=");
    var key = eq>-1 ? part.substr(0,eq) : part;
    var val = eq>-1 ? decodeURIComponent(part.substr(eq+1)) : "";
    var from = key.indexOf("[");
    if(from==-1) result[decodeURIComponent(key)] = val;
    else {
      var to = key.indexOf("]",from);
      var index = decodeURIComponent(key.substring(from+1,to));
      key = decodeURIComponent(key.substring(0,from));
      if(!result[key]) result[key] = [];
      if(!index) result[key].push(val);
      else result[key][index] = val;
    }
  });
  return result;
}`

**Comment by MaxProfit** [comment]
```javascript
var obj = getJsonFromUrl();
for(var key in obj) { // Array.forEach would skip string keys here
  console.log(key,":",obj[key]);
}

```

**Comment by MaxProfit** [comment]
```javascript
function setCookie(cname, cvalue, exseconds) {
  var d = new Date();
  d.setTime(d.getTime() + (exseconds*60*1000));
  var expires = "expires="+ d.toUTCString();
  document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
}

```

**Comment by MaxProfit** [comment]
```javascript
function getCookie(cname) {
  var name = cname + "=";
  var decodedCookie = decodeURIComponent(document.cookie);
  var ca = decodedCookie.split(';');
  for(var i = 0; i <ca.length; i++) {
    var c = ca[i];
    while (c.charAt(0) == ' ') {
      c = c.substring(1);
    }
    if (c.indexOf(name) == 0) {
      return c.substring(name.length, c.length);
    }
  }
  return "";
}
```

**Comment by roshinis78** [comment]
if (window.location.hash.length > 0) {
      for (let info of window.location.hash.split("&")) {
        let key_val = info.split("=");
        hashObject[key_val[0]] = key_val[1].substring(1);
      }
      console.log(hashObject);
    }
